# Copyright 2018, CS Systemes d'Information, http://www.c-s.fr
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
component:
    name: Kubernetes
    context:
        host: no
        cluster: dcos
    install:
        dcos:
            add:
                pace:
                    - package
                    - cli,config
                steps:
                    package:
                        targets:
                            masters: one
                        options:
                            dev: |
                                {
                                    "kubernetes": {
                                        "node_count": 1,
                                        "reserved_resources": {
                                            "kube_cpus": 1,
                                            "kube_mem": 1024,
                                            "kube_disk": 512
                                        }
                                    }
                                }

                            normal: |
                                {
                                    "kubernetes": {
                                        "high_availability": true,
                                        "node_count": 3,
                                        "reserved_resources": {
                                            "kube_cpus": 1,
                                            "kube_mem": 1024,
                                            "kube_disk": 512
                                        }
                                    }
                                }

                        run: |
                            output=$({{.dcos}} package install --yes kubernetes {{.options}} 2>&1)
                            rc=$?
                            [ $rc -ne 0 ] && {
                                echo $output
                                echo $output | grep "already installed" &>/dev/null || exit $rc
                            }
                            exit 0

                    cli:
                        targets:
                            masters: all
                        run: |
                            {{.dcos}} package install --yes kubernetes --cli

                    config:
                        targets:
                            masters: one
                        run: |
                            wait_complete() {
                                while [ 0 ]; do
                                    {{.dcos}} kubernetes plan show deploy | grep "scheduler (" | grep COMPLETE &>/dev/null && break
                                done
                            }
                            export -f wait_complete
                            bg_start WC 10 wait_complete
                            bg_wait WC 512
                            {{.dcos}} kubernetes kubeconfig --apiserver-url https://apiserver.kubernetes.l4lb.thisdcos.directory:6443 && \
                            {{.kubectl}} config set-cluster kubernetes --server https://apiserver.kubernetes.l4lb.thisdcos.directory:6443

            check: |
                {{.dcos}} kubernetes plan show deploy --json | jq .status | grep COMPLETE

            remove: |
                pace:
                    - remove
                steps:
                    remove:
                        target:
                            masters: one
                        run: |
                        {{.dcos}} package remove --yes kubernetes

...