#!/usr/bin/env bash
#
# Copyright 2018, CS Systemes d'Information, http://www.c-s.fr
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# install_docker.sh
#
# Installs Docker

---
component:
    name: tigerVNC
    targeting:
        host: no
        cluster:
            master: all
            node:
                private: no
                public: no
    installing:
        script:
            check: |
                case $LINUX_KIND in
                    centos|redhat)
                        yum list installed tigervnc &>/dev/null
                        ;;
                    debian|ubuntu)
                        dpkg-query -s tigervnc-standalone-server &>/dev/null
                        ;;
                    *)
                        echo "unsupported OS type '$LINUX_KIND'"
                        exit 1;;
                esac

            install: |
                # Configure Xvnc parameters
                mkdir -p ~cladm/.vnc
                cat >~cladm/.vnc/xstartup <<-'EOF'
                #!/bin/sh
                unset SESSION_MANAGER
                unset DBUS_SESSION_BUS_ADDRESS
                export DISPLAY=:0
                exec startxfce4
                EOF
                chmod u+rx ~cladm/.vnc/xstartup

                cat >~cladm/.vnc/config <<-'EOF'
                screen=0 1600x900x24
                geometry=1600x900
                desktop={{ .ClusterName }}-master-{{ .MasterIndex }}
                passwordfile=
                extension=GLX
                noreset
                SecurityTypes=None
                ZlibLevel=0
                EOF
                chown -R cladm:cladm ~cladm/.vnc

                case $LINUX_KIND in
                    centos|redhat)
                        yum install -y -t tigervnc-server && \
                        cp -s /lib/systemd/system/vncserver\@.service /etc/systemd/system/vncserver\@:0.service && \
                        sed -i -e "s/<USER>/{{ .Username }}/g" /etc/systemd/system/vncserver\@:0.service && \
                        systemctl daemon-reload && \
                        systemctl enable vncserver\@:0.service || exit $?
                        systemctl restart vncserver\@:0.service
                        ;;
                    debian|ubuntu)
                        if "$VERSION_ID" = "16.04" ]; then
                            wget -O tigervnc.tar.gz https://bintray.com/tigervnc/stable/download_file?file_path=tigervnc-1.9.0.x86_64.tar.gz && \
                            tar --strip-components=1 -zxvf tigervnc.tar.gz -C / || exit $?
                            rm -rf tigervnc.tar.gz
                        else
                            wait_for_apt && apt install -y tigervnc-standalone-server || exit $?
                        fi
                        cp -s /lib/systemd/system/vncserver\@.service /etc/systemd/system/vncserver\@:0.service && \
                        sed -i -e "s/<USER>/{{ .Username }}/g" /etc/systemd/system/vncserver\@:0.service && \
                        systemctl daemon-reload && \
                        systemctl enable vncserver\@:0.service || exit $?
                        systemctl restart vncserver\@:0.service
                        ;;
                    *)
                        echo "unsupported OS type '$LINUX_KIND'"
                        exit 1;;
                    esac

            uninstall: |
                case $LINUX_KIND in
                    centos|redhat)
                        yum install -y -t tigervnc-server xorg-x11-fonts-Type1 firefox && \
                        cp -s /lib/systemd/system/vncserver\@.service /etc/systemd/system/vncserver\@:0.service && \
                        sed -i -e "s/<USER>/cladm/g" /etc/systemd/system/vncserver\@:0.service && \
                        systemctl daemon-reload && \
                        systemctl enable vncserver\@:0.service || exit $?
                        systemctl restart vncserver\@:0.service
                        ;;
                    debian|ubuntu)
                        wait_for_apt && apt install -y tigervnc-standalone-server && \
                        cp -s /lib/systemd/system/vncserver\@.service /etc/systemd/system/vncserver\@:0.service && \
                        sed -i -e "s/<USER>/cladm/g" /etc/systemd/system/vncserver\@:0.service && \
                        systemctl daemon-reload && \
                        systemctl enable vncserver\@:0.service || exit $?
                        systemctl restart vncserver\@:0.service
                        ;;
                    *)
                        echo "unsupported OS type '$LINUX_KIND'"
                        exit 1;;
                esac
...
